trigger:
  - main
  - develop

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  NODE_CACHE_FOLDER: $(Pipeline.Workspace)/npm
  DOCKER_REPOSITORY: your-dockerhub-username
  IMAGE_TAG: $(Build.BuildId)

stages:
- stage: Build
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'MoneyWise-SonarQube'
        scannerMode: 'CLI'
        configMode: 'file'
        configFile: 'sonar-project.properties'

    - task: Maven@3
      inputs:
        mavenPomFile: 'backend/pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '17'
        mavenVersionOption: 'Default'
        sonarQubeRunAnalysis: true

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: |
        cd frontend
        npm install
        npm run build
      displayName: 'Build Frontend'

    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'

    - task: Docker@2
      inputs:
        containerRegistry: 'MoneyWise-DockerHub'
        repository: '$(DOCKER_REPOSITORY)/moneywise-backend'
        command: 'buildAndPush'
        Dockerfile: 'backend/Dockerfile'
        tags: |
          $(IMAGE_TAG)
          latest

    - task: Docker@2
      inputs:
        containerRegistry: 'MoneyWise-DockerHub'
        repository: '$(DOCKER_REPOSITORY)/moneywise-frontend'
        command: 'buildAndPush'
        Dockerfile: 'frontend/Dockerfile'
        tags: |
          $(IMAGE_TAG)
          latest
