global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'moneywise'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
