trigger: none # Déclenché manuellement après CI

pool:
  vmImage: 'ubuntu-latest'

steps:
# Déploiement Backend
- task: Docker@2
  inputs:
    command: 'run'
    arguments: '-d -p 8080:8080 --name moneywise-backend moneywise-backend:latest'

# Déploiement Frontend
- task: Docker@2
  inputs:
    command: 'run'
    arguments: '-d -p 3000:3000 --name moneywise-frontend moneywise-frontend:latest'

# Test simple
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Attendre que les services démarrent
      sleep 10
      
      # Vérifier que les services sont accessibles
      curl http://localhost:8080/health
      curl http://localhost:3000
      
      echo "Déploiement terminé avec succès"
