trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Build Backend
- task: Maven@3
  inputs:
    mavenPomFile: 'backend/pom.xml'
    goals: 'clean package'

# Build Frontend
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'frontend'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'frontend'
    customCommand: 'run build'

# Build et Push Docker Images
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: 'backend/Dockerfile'
    repository: 'moneywise-backend'
    tags: |
      $(Build.BuildNumber)
      latest

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: 'frontend/Dockerfile'
    repository: 'moneywise-frontend'
    tags: |
      $(Build.BuildNumber)
      latest
