---
- name: Deploy MoneyWise Application
  hosts: iis_servers
  vars:
    app_pool_name: "MoneyWise-{{ env }}"
    website_name: "MoneyWise-{{ env }}"
    website_port: 80
    dotnet_version: "v4.0"
    
  tasks:
    - name: Install IIS
      win_feature:
        name: Web-Server
        state: present
        include_management_tools: yes
      
    - name: Install ASP.NET 4.5
      win_feature:
        name: Web-Asp-Net45
        state: present

    - name: Create Application Pool
      win_iis_webapppool:
        name: "{{ app_pool_name }}"
        state: present
        attributes:
          managedRuntimeVersion: "{{ dotnet_version }}"
          startMode: AlwaysRunning

    - name: Create Website Directory
      win_file:
        path: "C:\\inetpub\\wwwroot\\{{ website_name }}"
        state: directory

    - name: Copy Application Files
      win_copy:
        src: "{{ playbook_dir }}/../../drop/"
        dest: "C:\\inetpub\\wwwroot\\{{ website_name }}"

    - name: Create Website
      win_iis_website:
        name: "{{ website_name }}"
        state: started
        port: "{{ website_port }}"
        physical_path: "C:\\inetpub\\wwwroot\\{{ website_name }}"
        application_pool: "{{ app_pool_name }}"
